---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: opensearch-1password-sa-token-release
  namespace: jenkins-prod
spec:
  secretStoreRef:
    kind: SecretStore
    name: onepassword-releng
  target:
    creationPolicy: Owner
  data:
    - secretKey: credential
      remoteRef:
        key: Opensearch 1Password svc-opensearch-release/credential
