apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jenkins-staging
  namespace: argocd
spec:
  project: jenkins
  sources:
    # helm chart source
    - repoURL: https://github.com/opensearch-project/jenkins-gitops
      targetRevision: main
      path: base/jenkins
      helm:
        valueFiles:
          - $gitops/staging/values.yaml

    # values source for chart above (via `ref`)
    - repoURL: https://github.com/opensearch-project/jenkins-gitops
      targetRevision: main
      ref: gitops

    # additional manifests outside the chart
    - repoURL: https://github.com/opensearch-project/jenkins-gitops
      targetRevision: main
      path: custom-resources/staging
  destination:
    server: https://kubernetes.default.svc
    namespace: jenkins-staging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
