apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jenkins-staging
  namespace: argocd
spec:
  project: jenkins
  sources:
    - repoURL: https://github.com/opensearch-project/jenkins-gitops
      targetRevision: main
      path: base/jenkins
      helm:
        valueFiles:
          - ../../staging/values.yaml
    - repoURL: https://github.com/opensearch-project/jenkins-gitops
      targetRevision: main
      path: custom-resources/staging
  destination:
    server: https://kubernetes.default.svc
    namespace: jenkins-staging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
